[project]
name = "stat-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiofiles",
    "alembic",
    "fastapi-pagination",
    "fastapi",
    "strawberry-graphql",
    "httpx",
    "python-dotenv",
    "python-multipart",
    "sqlalchemy",
    "uuid",
    "uvicorn",
    "pydantic-settings",
    "apscheduler",
    "pwdlib[argon2]",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
lint = [
    "flake8>=7.2.0",
]
