[project]
name = "stat-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiofiles",
    "alembic",
    "fastapi-pagination",
    "fastapi",
    "strawberry-graphql",
    "httpx",
    "python-dotenv",
    "python-multipart",
    "sqlalchemy[asyncio]",
    "uuid",
    "uvicorn",
    "pydantic-settings",
    "apscheduler",
    "pwdlib[argon2]",
    "argparse",
    "transliterate",
    "aiosqlite",
    "asyncpg",
]

[dependency-groups]
dev = [
    "pytest",
]
lint = [
    "flake8",
]
